version: '3'
services:
  vpronginx:
    build:
      Context: /root/vprofile-repo/Docker-web
    image: krish1739/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

  vproapp:
    build:
      Context: /root/vprofile-repo/Docker-app
    image: krish1739/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vprodb:
    build:
      Context: /root/vprofile-repo/Docker-db
    image: krish1739/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

volumes:
  vprodbdata: {}
